[package]
name = "lexicon"
version = "0.1.0"
authors = ["alex0112 <alarsen0112@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
